language: python
python:
 - "3.5"

install:
  - pip install codecov

# command to run tests
script:
 - python -m unittest test_triangle
 - coverage run test_triangle.py

# Push the results back to codecov
after_success:
  - codecov